"""add_execution_logs_table

Revision ID: 96240941449e
Revises: 1f333dd928f9
Create Date: 2026-01-26 00:26:59.170693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96240941449e'
down_revision: Union[str, None] = '1f333dd928f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('step_execution_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('log_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['step_execution_id'], ['step_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_logs_step_execution_id'), 'execution_logs', ['step_execution_id'], unique=False)
    op.alter_column('step_executions', 'input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('step_executions', 'output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('steps', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('step_executions', 'output',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('step_executions', 'input',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_execution_logs_step_execution_id'), table_name='execution_logs')
    op.drop_table('execution_logs')
    # ### end Alembic commands ###
