"""Add validation schemas

Revision ID: ee442b97a522
Revises: 343cbd293fbd
Create Date: 2026-02-03 09:18:42.462849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee442b97a522'
down_revision: Union[str, None] = '343cbd293fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('input_schema', sa.JSON(), nullable=True))
    op.add_column('steps', sa.Column('output_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'output_schema')
    op.drop_column('steps', 'input_schema')
    # ### end Alembic commands ###
