"""Add timeout_seconds

Revision ID: 343cbd293fbd
Revises: d9f14ccfc165
Create Date: 2026-02-03 09:10:18.029693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add timeout_seconds

Revision ID: 343cbd293fbd
Revises: d9f14ccfc165
Create Date: 2026-02-03 09:10:18.029693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343cbd293fbd'
down_revision: Union[str, None] = 'd9f14ccfc165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('timeout_seconds', sa.Integer(), nullable=False, server_default='60'))
    op.drop_column('workflows', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('steps', 'timeout_seconds')
    # ### end Alembic commands ###
